TIMEBUTLER_SELECTORS = {
    "username": ['input[name="username"]', 'input[type="email"]', 'input[placeholder*="E-Mail"]', 'input[placeholder*="Benutzer"]'],
    "password": ['input[name="password"]', 'input[type="password"]', 'input[placeholder*="Passwort"]'],
    "login_button": ['button:has-text("Anmelden")', 'button[type="submit"]', 'input[type="submit"]'],
    "own_data": ['text="Eigene Daten"', 'a:has-text("Eigene Daten")', '[role="link"]:has-text("Eigene Daten")'],
    "work_time": ['text="Arbeitszeit eintragen"', 'a:has-text("Arbeitszeit eintragen")', '[role="link"]:has-text("Arbeitszeit")', 'text="Zeiterfassung"'],
    "date": ['input[name*="date"]', 'input[type="date"]', 'input[placeholder*="Datum"]', 'input:near(:text("Datum"))'],
    "project": ['select[name*="project"]', 'select:near(:text("Projekt"))', 'input[placeholder*="Projekt"]', '[role="combobox"]:near(:text("Projekt"))'],
    "category": ['select[name*="category"]', 'select:near(:text("Kategorie"))', 'input[placeholder*="Kategorie"]', '[role="combobox"]:near(:text("Kategorie"))'],
    "start": ['input[name*="start"]', 'input[placeholder*="Start"]', 'input:near(:text("Start"))'],
    "end": ['input[name*="end"]', 'input[placeholder*="Ende"]', 'input:near(:text("Ende"))'],
    "pause": ['input[name*="pause"]', 'input[placeholder*="Pause"]', 'input:near(:text("Pause"))'],
    "remark": ['textarea[name*="remark"]', 'textarea[placeholder*="Bemerk"]', 'textarea:near(:text("Bemerk"))'],
    "duplicate_markers": ['text="bereits"', 'text="vorhanden"', 'text="existiert"'],
    "save_button": ['button:has-text("Speichern")', '[role="button"]:has-text("Speichern")', 'input[value="Speichern"]'],
}
