KLASSENBUCH_SELECTORS = {
    "username": ['input[name="username"]', 'input[type="email"]', 'input[placeholder*="Benutzer"]', 'input[placeholder*="E-Mail"]'],
    "password": ['input[name="password"]', 'input[type="password"]', 'input[placeholder*="Passwort"]'],
    "login_button": ['button:has-text("Anmelden")', 'button[type="submit"]', 'input[type="submit"]'],
    "overview_markers": ['text="Themendokumentationen"', 'text="Offen"', 'table'],
    "edit_button": ['button:has-text("Bearbeiten")', 'a:has-text("Bearbeiten")', '[title*="Bearbeiten"]', '[aria-label*="Bearbeiten"]', 'a:has-text("Edit")'],
    "ue_tab": ['text="Unterrichtseinheiten"', 'button:has-text("Unterrichtseinheiten")', 'a:has-text("Unterrichtseinheiten")', 'text="UE"'],
    "content_fields": ['textarea', 'input[type="text"]', '[contenteditable="true"]'],
    "teaching_format_fields": ['button:has-text("Lernformat")', '[role="button"]:has-text("Lernformat")', 'button:has-text("Methodik")', '[role="button"]:has-text("Methodik")', 'input[placeholder*="Lernformat" i]', 'input[aria-label*="Lernformat" i]', 'select[name*="lernformat" i]', 'select[name*="methodik" i]'],
    "teaching_format_modal": ['[role="dialog"]:has-text("Lernformat")', '[role="dialog"]:has-text("Methodik")', '.modal:has-text("Lernformat")', '.modal:has-text("Methodik")', 'text="Aufgaben-/\u00dcbungsbesprechung"', 'text="betreute Einzelarbeit"'],
    "teaching_format_apply": ['button:has-text("\u00dcbernehmen")', '[role="button"]:has-text("\u00dcbernehmen")', 'button:has-text("Uebernehmen")', '[role="button"]:has-text("Uebernehmen")', 'button:has-text("Anwenden")', '[role="button"]:has-text("Anwenden")'],
    "save_button": ['button:has-text("Speichern")', '[role="button"]:has-text("Speichern")', 'input[value="Speichern"]'],
    "next_button": ['button:has-text("Weiter")', '[role="button"]:has-text("Weiter")', 'a:has-text("Weiter")'],
    "signature_page_markers": ['text="Signierung"', 'text="Signatur"', 'text="Unterschrift"', 'text="Vorschau"', 'button:has-text("Signieren")', 'button:has-text("Abschliessen")', 'button:has-text("Abschließen")'],
    "signature_canvas": ['canvas:near(:text("Signatur"))', 'canvas:near(:text("Unterschrift"))', 'canvas[aria-label*="Signatur" i]', 'canvas[aria-label*="Unterschrift" i]', '[data-testid*="signature" i] canvas', '[class*="signature" i] canvas', '[class*="unterschrift" i] canvas', 'canvas'],
    "signature": ['input[name*="sign" i]', 'input[name*="signature" i]', 'input[name*="unterschrift" i]', 'textarea[name*="sign" i]', 'textarea[name*="signature" i]', 'input[placeholder*="Signatur" i]', 'input[placeholder*="Unterschrift" i]', 'textarea[placeholder*="Signatur" i]', 'textarea[placeholder*="Unterschrift" i]', 'input[aria-label*="Signatur" i]', 'textarea[aria-label*="Signatur" i]', 'input:near(:text("Signatur"))', 'textarea:near(:text("Signatur"))', 'input:near(:text("Unterschrift"))', 'textarea:near(:text("Unterschrift"))'],
    "signature_confirm_checkbox": ['input[type="checkbox"][name*="confirm" i]', 'input[type="checkbox"][name*="bestaet" i]', 'label:has-text("bestätige") input[type="checkbox"]', 'label:has-text("korrekt") input[type="checkbox"]'],
    "sign_button": ['button:has-text("Speichern und signieren")', '[role="button"]:has-text("Speichern und signieren")', 'button:has-text("Signieren")', '[role="button"]:has-text("Signieren")', 'button:has-text("Abschliessen")', '[role="button"]:has-text("Abschliessen")', 'button:has-text("Abschließen")', '[role="button"]:has-text("Abschließen")', 'input[value*="Signieren"]', 'input[value*="Abschliessen"]', 'input[value*="Abschließen"]'],
    "signature_success": ['text="signiert"', 'text="abgeschlossen"', 'text="erfolgreich"', 'text="gespeichert"'],
    "manual_signature_markers": ['text="TAN"', 'text="2FA"', 'text="Zwei-Faktor"', 'text="Zertifikat"', 'text="Smartcard"', 'text="externer Signaturdienst"'],
}
